#!/bin/bash
source process-management

SUBCOMMAND_LIST += [
  "client"          "Connects to an existing VPN for observation only."
  "connector"       "Connects this system to a VPN and registers as a trusted node."
]