FROM voices-network-mw-framework

RUN dpkg -i --force-overwrite ${INSTALLATION_PACKAGE_PATH}/TENA-Console-v2.0.0@Product@u2004-gcc9-64-v51bb0659.deb
RUN dpkg -i --force-overwrite ${INSTALLATION_PACKAGE_PATH}/TENA-Canary-v1.0.13@Product@u2004-gcc9-64-vdbd87712.deb
