#!/bin/bash

sudo mkdir -p /opt/carma/carma-utils
sudo chown -r /opt/carma

sudo In /etc/profile, export:
- path with script subdirectories
- script root
- docker root
- utils root (/opt/carma/carma-utils)

upload ssh key
Download the repository to /opt/carma/carma-utils














#
#Make /opt/carma/carma-utils
#chown /opt/carma
#
#In /etc/profile, export:
#- path with script subdirectories
#- script root
#- docker root
#- utils root (/opt/carma/carma-utils)
#
#change to user
#upload ssh key
#Download the repository to /opt/carma/carma-utils
#


