#!/bin/bash

# ------------------------------------------------------------------------------
# Description
# ------------------------------------------------------------------------------

# Transfer files using curl with automated password authentication.

# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------

BIN_REPOSITORY_ROOT=host
BIN_REPOSITORY_AUTH=user:password

# ------------------------------------------------------------------------------
# Process Arguments
# ------------------------------------------------------------------------------

main() {

  # Call the relevant operation (1:1 mapping of command:function)
  COMMAND=$1
  shift
  $COMMAND $@
  exit 0
}


# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

push() {
  FILE_LOCALPATH=$1
  FILE_REMOTE_RELATIVE_PATH=$2
  curl -u $BIN_REPOSITORY_AUTH --upload-file $FILE_LOCALPATH $BIN_REPOSITORY_ROOT/$FILE_REMOTE_RELATIVE_PATH/$(basename $FILE_LOCALPATH)
}

pull() {
  FILE_REMOTE_PATH=$1
  FILE_LOCALPATH=$2
  if [[ -z $FILE_LOCALPATH ]]; then
    curl -v -u $BIN_REPOSITORY_AUTH -O $BIN_REPOSITORY_ROOT/$FILE_REMOTE_RELATIVE_PATH
  else
    mkdir -p $(dirname $FILE_LOCALPATH)
    curl -u $BIN_REPOSITORY_AUTH -o $FILE_LOCALPATH $BIN_REPOSITORY_ROOT/$FILE_REMOTE_RELATIVE_PATH
  fi
}

# ------------------------------------------------------------------------------
# Execute the script
# ------------------------------------------------------------------------------

main $@
