#!/bin/bash
source /home/carma/code/stol/carma-utilities-dg/voices/scripts/interfaces/container-management

echo "voices called with args: $@"

#DOCKERFILE_FULL_PATH=../../docker/
DOCKERFILE`_FULL_PATH=/home/carma/code/stol/carma-utilities-dg/voices/docker/network/Dockerfile-network-base
IMAGE_NAME=voices-network-base
CONTAINER_NAME=voices-network-base
CONTAINER_RUN_OPTIONS=

start() {
  # How will we specialize the starting procedure for the EM node?
  echo "voices start"
}

main $@
