#!/bin/bash
source carma-container-management

echo "voices called with args: $@"
echo "THIS_SCRIPT_DIR=$THIS_SCRIPT_DIR"

DOCKERFILE_FULL_PATH=$CARMA_DOCKER_ROOT/voices/network/Dockerfile-network-base
IMAGE_NAME=voices-network-base
CONTAINER_NAME=voices-network-base
CONTAINER_RUN_OPTIONS=

start() {
  # How will we specialize the starting procedure for the EM node?
  echo "voices start"
}

main $@
