#!/bin/bash
source container-management

echo "voices called with args: $@"

DOCKERFILE=../../docker/
IMAGE_NAME=
CONTAINER_NAME=
CONTAINER_RUN_OPTIONS=

start() {
  # How will we specialize the starting procedure for the EM node?
}

main $@
