#!/bin/bash
source ../interfaces/container-management.sh

DOCKERFILE=../../docker/
IMAGE_NAME=
CONTAINER_NAME=
CONTAINER_RUN_OPTIONS=

start() {
  # How will we specialize the starting procedure for the EM node?
}
