#!/bin/bash
source carma-container-management

# Configure a Sonatype Nexus binary repository
DOCKERFILE_FULL_PATH=$CARMA_DOCKER_ROOT/support/Dockerfile-support-nexus
IMAGE_NAME=sonatype/nexus3
CONTAINER_NAME=nexus
CONTAINER_RUN_OPTIONS="-d -p 8081:8081"

image name
container name
tag

#stop() {
#    docker stop --time=120 $CONTAINER_NAME
#}

main $@
