#!/bin/bash
source ${CARMA_SCRIPT_ROOT}/scripts-base/carma-process-management

# ------------------------------------------------------------------------------
# Description
# ------------------------------------------------------------------------------

# The Twingate Client connects to an existing VPN for observation only.

# ------------------------------------------------------------------------------
# Lifecycle Functions
# ------------------------------------------------------------------------------

configure() {
  echo
}

build() {
  echo
}

push() {
  echo
}

pull() {
  echo
}

install() {
  # Twingate vpn-client
  RUN curl -S 'https://binaries.twingate.com/client/linux/install.sh' | sudo bash
  #  RUN twingate setup --headless $HOME/.twingate/service_key.json
}

start() {
  echo
}

stop() {
  echo
}

monitor() {
  echo
}

# ------------------------------------------------------------------------------
# Specialized Functions
# ------------------------------------------------------------------------------
