#!/bin/bash
source ${CARMA_SCRIPT_ROOT}/scripts-base/carma-process-management

# ------------------------------------------------------------------------------
# Description
# ------------------------------------------------------------------------------

# The Twingate Connector connects this system to a VPN and registers as a trusted node.

# ------------------------------------------------------------------------------
# Lifecycle Functions
# ------------------------------------------------------------------------------

configure() {
  echo
}

build() {
  echo
}

push() {
  echo
}

pull() {
  echo
}

install() {
  echo "Connector MUST be configured with network administrator in the loop; no commands are available."
}

start() {
  echo
}

stop() {
  echo
}

monitor() {
  echo
}

# ------------------------------------------------------------------------------
# Specialized Functions
# ------------------------------------------------------------------------------
