#!/bin/bash
source bashbase

SUBCOMMAND_LIST += [
  "em"                  "Execution manager."
  "monitoring-tools"    "Tools used to monitor the MW layer."
  "adapters"            "Adapters which translate data between the MW and CARMA components."
]






install() {

  if [[ == "framework" ]]; then
#      dpkg --force-overwrite -i 'TENA-StandardOMsSDK-v2.0.0/TENA-StandardOMsSDK-v2.0.0@Product@u2004-gcc9-64-d-v99ae11aa.deb'
#      dpkg --force-overwrite -i 'TENA-Console-v2.0.1/TENA-Console-v2.0.1@Product@u2004-gcc9-64-v244836f9.deb'
#      dpkg --force-overwrite -i 'TENA-MiddlewareSDK-v6.0.9.A/TENA-MiddlewareSDK-v6.0.9.A@Product@u2004-gcc9-64-d-va3bc16dc.deb'
#      dpkg --force-overwrite -i 'TENA-Canary-v1.0.13/TENA-Canary-v1.0.13@Product@u2004-gcc9-64-vdbd87712.deb'

    #TENA Middleware
    ${HOST_INSTALLATION_PACKAGE_PATH}/TENA-MiddlewareSDK-v${TENA_VERSION}.B@Product@${TENA_PLATFORM}-va0b09d44.bin -i /home --auto

    #VUG Combined Distribution OM
    ${HOST_INSTALLATION_PACKAGE_PATH}/VUG-VOICES-Combined-Distribution-v0.12.0@Product@${TENA_PLATFORM}-v1976e608.bin -i /home --auto

    #TENA Boost
    ${HOST_INSTALLATION_PACKAGE_PATH}/TENA-boost-v1.77.0.1@Product@${TENA_PLATFORM}-vall.bin -i /home --auto

  elif [[ == "monitor" ]]; then
    # TODO Veriffy .org not .mil
    # middlewareSDK
    dpkg -i --force-overwrite ${HOST_INSTALLATION_PACKAGE_PATH}/TENA-Console-v2.0.0@Product@u2004-gcc9-64-v51bb0659.deb
    dpkg -i --force-overwrite ${HOST_INSTALLATION_PACKAGE_PATH}/TENA-Canary-v1.0.13@Product@u2004-gcc9-64-vdbd87712.deb

  elif [[ == "adapters" ]]; then

#  cp * ${TENA_HOME}/lib  # Copy custom TENA libraries to system
#  cp tena-cmake-package ${TENA_HOME}/lib



#      Intelligently selects which layer to interface with and uses relevant script.
#
#    Commands:
#      build <component>       Build the component.
#      install <component>     Install the component.
#      start <component>       Start the component.
#      monitor <component>     Monitor the component.
#      --help              Print this help information.
#

    # Pull pre-built adapters OR build from source??
    echo "Unsure if this should pull pre-built adapters or build from source."

  fi

}

monitor() {
  /opt/TENA/Console-v2.0.1/start.sh &
  /opt/TENA/tenaCanary-v1.0.12/start.sh &
}



start() {
  # Start the Execution Manager from command line; easier to launch from the Console GUI
  TENA_LISTEN_ENDPOINT_IP=
  TENA_LISTEN_ENDPOINT_PORT=
  TENA_MULTICAST_ENDPOINT_IP=
  TENA_MULTICAST_ENDPOINT_PORT=

  $TENA_HOME/executionManager-v${TENA_VERSION}/start.sh \
    -listenEndpoints ${TENA_LISTEN_ENDPOINT_IP}:${TENA_LISTEN_ENDPOINT_PORT} \
    -multicastProperties ${TENA_MULTICAST_ENDPOINT_IP}:${TENA_MULTICAST_ENDPOINT_PORT}
}




