#!/bin/bash

# ------------------------------------------------------------------------------
# Description
# ------------------------------------------------------------------------------

# Commands to configure and interact with the VOICES network.

# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------

# Description
DESCRIPTION="Control script for this project."

# Define a set of commands
declare -A COMMAND_LIST
COMMAND_LIST["help"]="Print this help information."
COMMAND_LIST["build"]="Build the docker image."
COMMAND_LIST["run"]="Run the container."

# Locate this base script
THIS_COMMAND=$(basename $BASH_SOURCE)
CARMA_INSTALL_ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Global environment variables
CARMA_UTILITIES_ROOT=$CARMA_INSTALL_ROOT/carma-utils
CARMA_SCRIPT_ROOT=$CARMA_UTILITIES_ROOT/scripts
CARMA_DOCKER_ROOT=$CARMA_UTILITIES_ROOT/docker

# Docker parameters
DOCKER_IMAGE_NAME=voices
DOCKER_CONTAINER_NAME=voices
DOCKER_DOCKERFILE_FULL_PATH=$CARMA_DOCKER_ROOT/$DOCKER_IMAGE_NAME/Dockerfile
DOCKER_CONTAINER_RUN_OPTIONS="--entrypoint /bin/bash --rm"

# Paths
HOST_INSTALLATION_PACKAGE_PATH=$HOME/carma/installation-packages
DOCKER_BUILD_SPACE=$CARMA_UTILITIES_ROOT

# ------------------------------------------------------------------------------
# Main Loop
# ------------------------------------------------------------------------------

main() {

  # Call the relevant operation (1:1 mapping of command:function)
  COMMAND=$1
  shift
  $COMMAND $@

  exit 0
}

# ------------------------------------------------------------------------------
# Command Functions
# ------------------------------------------------------------------------------

help() {
  printf "%s\n" "$0 <command> <args>"
  printf "\n"
  printf "%s\n" "$DESCRIPTION"
  printf "\n"
  printf "Commands:\n"
  for COM in ${!COMMAND_LIST[@]}; do
    printf "\t%s\t\t\t%s\n" "$COM" "${COMMAND_LIST[$COM]}"
  done
  printf "\n"
}

build() {
  sudo docker build -t $DOCKER_IMAGE_NAME:latest -f $DOCKER_DOCKERFILE_FULL_PATH $DOCKER_BUILD_SPACE
}

run() {
  sudo docker run $DOCKER_CONTAINER_RUN_OPTIONS --name $DOCKER_CONTAINER_NAME:latest $DOCKER_IMAGE_NAME:latest
  docker exec -it $DOCKER_CONTAINER_NAME:latest /bin/bash
}

# ------------------------------------------------------------------------------
# Execute the script
# ------------------------------------------------------------------------------

main $@
