FROM voices-network-mw-monitor

ENV CARMA_INSTALL_ROOT=/opt/carma
ENV CARMA_UTILITIES_ROOT=/opt/carma/carma-utils
ENV CARMA_SCRIPT_ROOT=/opt/carma/carma-utils/scripts
ENV CARMA_DOCKER_ROOT=/opt/carma/carma-utils/docker

ENV PATH="${PATH}:/opt/carma/carma-utils/scripts:/opt/carma/carma-utils/scripts/scripts-base:/opt/carma/carma-utils/scripts/support:/opt/carma/carma-utils/scripts/voices:/opt/carma/carma-utils/scripts/voices/process:/opt/carma/carma-utils/scripts/voices/process/mw-scripts:/opt/carma/carma-utils/scripts/voices/process/net-scripts"

COPY .source-repositories/tena-traffic-light-entity-generator /opt/carma/voices/mw-adapters/tena-traffic-light-entity-generator
COPY .source-repositories/tena-j2735-message-adapter /opt/carma/voices/mw-adapters/tena-j2735-message-adapter

COPY .source-repositories/tena-cmake-package/cmake /opt/TENA/lib/cmake

# Development tools
RUN apt-get install -y libxrender1
COPY .binaries/mw-adapters/CLion-2022.3.1.tar.gz /tmp/
RUN mkdir -p /opt/carma/voices/mw-adapters
RUN tar -xf /tmp/CLion-2022.3.1.tar.gz -C /opt/carma/voices/mw-adapters
#RUN snap install clion








#RUN mw install adapters
#RUN mkdir -p ~/.ssh

#COPY id_rsa ~/.ssh
#COPY id_rsa.pub ~/.ssh
#COPY known_hosts ~/.ssh
#
#RUN chmod -w ~/
#RUN chmod 700 -R ~/.ssh
#RUN find ~/.ssh/ -name "id_*" -exec chmod 600 {} +
#RUN find ~/.ssh/ -name "id*pub*" -exec chmod 644 {} +
#RUN touch  ~/.ssh/authorized_keys  ~/.ssh/known_hosts
#RUN chmod 640 ~/.ssh/authorized_keys
#RUN chmod 640 ~/.ssh/known_hosts
#
#RUN git clone -o StrictHostKeyChecking=no git@github.com:davidgayman/tena-traffic-light-entity-generator-dg.git /opt/carma/voices/mw-adapters/tena-traffic-light-entity-generator
#RUN git clone -o StrictHostKeyChecking=no git@github.com:usdot-fhwa-stol/tena-j2735-message-adapter.git /opt/carma/voices/mw-adapters/tena-j2735-message-adapter

