FROM voices-network-vpn:latest

ENV TENA_HOME=/opt
ENV TENA_VERSION=6.0.8
ENV TENA_PLATFORM=u2004-gcc9-64
ENV VUG_INSTALL_DIR=/opt/carma/TENA-VUG

RUN mkdir -p $TENA_HOME/TENA
RUN mkdir -p $VUG_INSTALL_DIR
RUN mkdir -p /tmp/binaries-mw-framework
COPY ./.binaries/mw-framework /tmp/binaries-mw-framework

RUN /tmp/binaries-mw-framework/TENA-MiddlewareSDK-v6.0.8.B@Product@u2004-gcc9-64-va0b09d44.bin -i $TENA_HOME --auto
RUN /tmp/binaries-mw-framework/TENA-StandardOMsSDK-v2.0.0@Product@u2004-gcc9-64-v54c2ccf3.bin -i $TENA_HOME --auto
RUN /tmp/binaries-mw-framework/VUG-VOICES-Combined-Distribution-v0.12.0@Product@u2004-gcc9-64-v1976e608.bin -i $TENA_HOME --auto
RUN /tmp/binaries-mw-framework/VUG-j2735-Distribution-v0.1.1@Product@u2004-gcc9-64-vf9c7e345.bin -i $TENA_HOME --auto
