FROM ubuntu:20.04

# Set up system environment
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/New_York"
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y snapd
RUN systemctl enable snapd
RUN apt-get install -y git vim tree

# Copy scripts in
RUN mkdir -p /opt/carma/carma-utils
COPY scripts /opt/carma/carma-utils/scripts
