#!/bin/bash
source ${CARMA_SCRIPT_ROOT}/scripts-base/carma-bashbase

# Define the following in subscripts:
# <...>

# Standardized build paths
BUILD_SUBPATH=__build

# Typical lifecycle: build -> install -> start -> monitor
COMMAND_LIST["configure"]="Configure the dependencies and environment to enable a build by way of the \`build\` command or a development environment."
COMMAND_LIST["build"]="Compile and package the solution."
COMMAND_LIST["push"]="Push the package to the global repository."

COMMAND_LIST["pull"]="Pull a pre-built package."
COMMAND_LIST["install"]="Install to the system."
COMMAND_LIST["start"]="Launch the program."
COMMAND_LIST["stop"]="Stop the program."
COMMAND_LIST["monitor"]="Launch monitoring tools for the program."
