#!/bin/bash
source carma-container-management

# Constants
CONTAINER_CARMA_INSTALL_ROOT=/opt/carma
CONTAINER_CARMA_UTILITIES_ROOT=/opt/carma/carma-utils
CONTAINER_CARMA_SCRIPT_ROOT=/opt/carma/carma-utils/scripts
CONTAINER_CARMA_DOCKER_ROOT=/opt/carma/carma-utils/docker
CONTAINER_PATH_ADDITIONS="/home/carma/code/stol/carma-utils/scripts:/home/carma/code/stol/carma-utils/scripts/scripts-base:/home/carma/code/stol/carma-utils/scripts/support:/home/carma/code/stol/carma-utils/scripts/voices:/home/carma/code/stol/carma-utils/scripts/voices/process:/home/carma/code/stol/carma-utils/scripts/voices/process/mw-scripts:/home/carma/code/stol/carma-utils/scripts/voices/process/net-scripts"

# Parameters
DOCKER_CONTAINER_NAME=voices-network

DOCKER_IMAGE_NAME_APPEND_LIST=(
  base
  tools
  vpn
#  mw-framework
#  mw-monitor
#  mw-adapters
  )

DOCKER_CONTAINER_RUN_OPTIONS=

DOCKER_CONTAINER_ENV="--env CARMA_INSTALL_ROOT=$CONTAINER_CARMA_INSTALL_ROOT
  --env CARMA_UTILITIES_ROOT=$CONTAINER_CARMA_UTILITIES_ROOT
  --env CARMA_SCRIPT_ROOT=$CONTAINER_CARMA_SCRIPT_ROOT
  --env CARMA_DOCKER_ROOT=$CONTAINER_CARMA_DOCKER_ROOT
  --env PATH_ADDITIONS=$CONTAINER_PATH_ADDITIONS
  "

DOCKER_BUILD_ENV="
  --build-arg CARMA_INSTALL_ROOT=$CONTAINER_CARMA_INSTALL_ROOT
  --build-arg CARMA_UTILITIES_ROOT=$CONTAINER_CARMA_UTILITIES_ROOT
  --build-arg CARMA_SCRIPT_ROOT=$CONTAINER_CARMA_SCRIPT_ROOT
  --build-arg CARMA_DOCKER_ROOT=$CONTAINER_CARMA_DOCKER_ROOT
  --build-arg PATH_ADDITIONS=$CONTAINER_PATH_ADDITIONS
  "

start() {
  # How will we specialize the starting procedure for the EM node?
  echo "voices start"
}

main $@
